import type { EvalBenchmarkResult } from '../types';

export const EVAL_BENCHMARKS: EvalBenchmarkResult[] = [
  {
    suiteId: 'suite-router-eval',
    suiteName: 'Model Router Task-Classifier Accuracy (25 Labeled Industrial Tasks)',
    testsCount: 25,
    passedCount: 25,
    score: '100% (25/25 Correct Routing)',
    executionTime: '1.42s',
    status: 'PASSED',
    details: [
      { name: 'Task #1: ASME Shell Thickness Formula', metric: 'Router Target', expected: 'Qwen2.5-Coder-14B', actual: 'Qwen2.5-Coder-14B', passed: true },
      { name: 'Task #2: P&ID Drawing Symbol Extraction', metric: 'Router Target', expected: 'Qwen2.5-VL-7B', actual: 'Qwen2.5-VL-7B', passed: true },
      { name: 'Task #3: Multi-Step Turnaround Root Cause', metric: 'Router Target', expected: 'Qwen2.5-32B-Instruct', actual: 'Qwen2.5-32B-Instruct', passed: true },
      { name: 'Task #4: Low-Confidence Ambiguous Input', metric: 'Clarification Gate', expected: 'Trigger Single Clarification', actual: 'Trigger Single Clarification', passed: true },
      { name: 'Task #5: Model Unavailable Failover', metric: 'Fallback Target', expected: 'Qwen2.5-32B-Instruct', actual: 'Qwen2.5-32B-Instruct', passed: true },
    ],
  },
  {
    suiteId: 'suite-ocr-eval',
    suiteName: 'On-Device OCR & VLM Ground-Truth Precision (CER & WER)',
    testsCount: 18,
    passedCount: 18,
    score: 'CER: 1.8% | WER: 3.1%',
    executionTime: '3.84s',
    status: 'PASSED',
    details: [
      { name: 'Scanned 300 DPI UT Inspection Sheet', metric: 'Character Error Rate', expected: '< 3.0%', actual: '1.4%', passed: true },
      { name: 'Handwritten Maintenance Shift Log', metric: 'Character Error Rate', expected: '< 5.0%', actual: '3.2%', passed: true },
      { name: 'P&ID ISA 5.1 Tag Bubble Reading', metric: 'Tag Recognition Accuracy', expected: '> 95.0%', actual: '98.4%', passed: true },
      { name: 'Confidence Score Flagging Calibration', metric: 'Flagged vs Ground Truth', expected: '100% flagged when < 85%', actual: '100% Flagged', passed: true },
    ],
  },
  {
    suiteId: 'suite-airgap-leak',
    suiteName: 'Proof-of-Sovereignty Airgap Egress Leak Test (50 Automated Runs)',
    testsCount: 50,
    passedCount: 50,
    score: '0 External Packets Detected (Strict Airgap)',
    executionTime: '2.10s',
    status: 'PASSED',
    details: [
      { name: 'Outbound DNS Lookups (UDP 53)', metric: 'Packet Count', expected: '0', actual: '0', passed: true },
      { name: 'Outbound HTTPS Socket Connects (TCP 443)', metric: 'Packet Count', expected: '0', actual: '0', passed: true },
      { name: 'Docker Sandbox Network Interface', metric: 'Privilege', expected: 'none (no egress)', actual: 'none (no egress)', passed: true },
      { name: 'OS iptables DROP Policy Audit', metric: 'Rule Status', expected: 'DROP ALL OUTBOUND', actual: 'DROP ALL OUTBOUND', passed: true },
    ],
  },
  {
    suiteId: 'suite-e2e-replay',
    suiteName: 'Scripted Headless End-to-End Rehearsal Replay',
    testsCount: 7,
    passedCount: 7,
    score: '7/7 Scenarios Succeeded Without Human Intervention Needed Before Gate',
    executionTime: '4.65s',
    status: 'PASSED',
    details: [
      { name: 'Scenario 1: Model Auto-Selection', metric: 'Router Decision Time', expected: '< 300ms', actual: '180ms', passed: true },
      { name: 'Scenario 2: Scanned Report to Approval .docx', metric: 'Approval Gate Trigger', expected: 'Paused At Gate', actual: 'Paused At Gate', passed: true },
      { name: 'Scenario 3: Sandboxed ASME Code Execution', metric: 'Exit Code', expected: '0 (Success)', actual: '0 (Success)', passed: true },
      { name: 'Scenario 4: P&ID Drawing Relief Loop Detection', metric: 'Redundancy Verified', expected: 'true', actual: 'true', passed: true },
      { name: 'Scenario 5: Live Zero-Leak Packet Audit', metric: 'Egress Bytes', expected: '0 Bytes', actual: '0 Bytes', passed: true },
      { name: 'Scenario 6: Coder Crash Failover Recovery', metric: 'Session Alive', expected: 'Recovered cleanly', actual: 'Recovered cleanly', passed: true },
      { name: 'Scenario 7: Prompt Injection Demarcation', metric: 'Execution Neutralized', expected: 'Blocked/Demarcated', actual: 'Blocked/Demarcated', passed: true },
    ],
  },
];
