import type { ModelInfo } from '../types';

export const INITIAL_MODELS: ModelInfo[] = [
  {
    id: 'qwen-32b-reasoning',
    name: 'Qwen2.5-32B-Instruct',
    role: 'Primary Reasoning & Plan-Execute Agent Core',
    primaryTasks: ['ReAct multi-step planning', 'Tool dispatch orchestration', 'Root-cause synthesis', 'Fallback generalist'],
    quantization: '4-bit AWQ (On-Device)',
    adapter: 'vLLM',
    vramUsageGb: 13.8,
    allocatedVramGb: 16.0,
    contextWindow: '32,768 tokens',
    status: 'ACTIVE',
    accuracyRate: 99.2,
  },
  {
    id: 'qwen-coder-14b',
    name: 'Qwen2.5-Coder-14B',
    role: 'Isolated Code Sandbox & Spreadsheet Engine',
    primaryTasks: ['Shell stress calculus', 'Corrosion rate modeling', 'Excel openpyxl generation', 'Isolated Python execution'],
    quantization: '4-bit GPTQ (No-Internet)',
    adapter: 'Ollama',
    vramUsageGb: 8.2,
    allocatedVramGb: 10.0,
    contextWindow: '32,768 tokens',
    status: 'READY',
    accuracyRate: 97.8,
    isFallbackFor: 'General math & code syntax',
  },
  {
    id: 'qwen-vl-7b',
    name: 'Qwen2.5-VL-7B',
    role: 'Multimodal VLM & P&ID Drawing Understanding',
    primaryTasks: ['P&ID valve & loop detection', 'Scanned refinery report OCR', 'Corrosion graph inspection', 'Handwritten maintenance logs'],
    quantization: '4-bit AWQ (Airgapped)',
    adapter: 'vLLM',
    vramUsageGb: 5.4,
    allocatedVramGb: 6.5,
    contextWindow: '16,384 tokens',
    status: 'READY',
    accuracyRate: 98.6,
  },
  {
    id: 'bge-large-embed',
    name: 'BGE-Large-EN-v1.5',
    role: 'Local Vector Store Embeddings (Chroma/Qdrant)',
    primaryTasks: ['MRPL synthetic SOP retrieval', 'API 510 code similarity', 'Airgapped semantic chunking', 'Citation verification'],
    quantization: 'FP16 (Dense Embedding)',
    adapter: 'Torch (Airgapped)',
    vramUsageGb: 1.2,
    allocatedVramGb: 2.0,
    contextWindow: '512 tokens / chunk',
    status: 'READY',
    accuracyRate: 99.7,
  },
];

export const ROUTER_BENCHMARK_MATRIX = [
  { taskType: 'Code Sandbox & Formula Generation', preferredModel: 'Qwen2.5-Coder-14B', accuracy: '98.8%', latencyMs: 420, fallbackTarget: 'Qwen2.5-32B' },
  { taskType: 'P&ID Diagram & Drawing Analysis', preferredModel: 'Qwen2.5-VL-7B', accuracy: '97.4%', latencyMs: 780, fallbackTarget: 'PaddleOCR + 32B' },
  { taskType: 'Complex ReAct Multi-Step Planning', preferredModel: 'Qwen2.5-32B-Instruct', accuracy: '99.1%', latencyMs: 640, fallbackTarget: 'Qwen2.5-14B (Quantized)' },
  { taskType: 'Scanned Document OCR Ingestion', preferredModel: 'Qwen2.5-VL-7B / PaddleOCR', accuracy: '98.2%', latencyMs: 510, fallbackTarget: 'Tesseract Local' },
  { taskType: 'SOP Grounding & Vector Retrieval', preferredModel: 'BGE-Large + Qwen2.5-32B', accuracy: '99.5%', latencyMs: 190, fallbackTarget: 'BM25 Local Keyword' },
];
