import type { SOPDocument } from '../types';

export const SYNTHETIC_SOPS: SOPDocument[] = [
  {
    id: 'sop-cru-402',
    code: 'MRPL-SOP-CRU-402',
    title: 'Crude Distillation Column Shell Inspection & Corrosion Thresholds',
    category: 'SOP',
    unit: 'CDU-II / Column CRU-C-101',
    updatedAt: '2026-03-15',
    chunksCount: 7,
    summary: 'Defines mandatory inspection intervals, ultrasonic thickness scanning patterns, and minimum retirement thickness equations for Column CRU-C-101 and intermediate shell sectors.',
    sampleChunks: [
      {
        id: 'chk-cru-402-1',
        section: 'Section 4: Minimum Retirement Thickness Criteria',
        content: 'The absolute minimum retirement thickness (t_min) for the intermediate shell courses (Trays 10 to 22) is calculated as t_min = (P * R) / (S * E - 0.6 * P) = 6.20 mm including ASME Section VIII margins. When measured residual thickness falls below 8.00 mm, the baseline 36-month inspection cycle must be halved to 18 months.',
        relevanceTag: 'Retirement Threshold (6.20mm) & 18M Interval',
      },
      {
        id: 'chk-cru-402-2',
        section: 'Section 3: Ultrasonic Thickness (UT) Scanning Grid',
        content: 'Ultrasonic thickness measurements must be acquired using a calibrated dual-crystal probe at 5.0 MHz. A minimum of 16 measurement points per tray elevation must be logged across 4 cardinal quadrants (0, 90, 180, 270 deg). Readings with coupling confidence below 85% must be rescanned.',
        relevanceTag: 'UT Calibration & 85% Coupling',
      },
      {
        id: 'chk-cru-402-3',
        section: 'Section 6: Human Sign-off & Filing Protocol',
        content: 'Any recommendation to reduce inspection intervals or operate with localized thinning requires formal plant sign-off: preparation of formal Technical Approval Note, review by Chief Plant Inspector (Level III NDT), and final sign-off by Plant Operations Manager.',
        relevanceTag: 'Supervisor Sign-off Mandate',
      },
    ],
  },
  {
    id: 'api-510-pv',
    code: 'MRPL-STD-API-510',
    title: 'In-Service Pressure Vessel Inspection & Remaining Life Calculation',
    category: 'Inspection Code',
    unit: 'Refinery Wide Pressure Vessels',
    updatedAt: '2025-09-30',
    chunksCount: 4,
    summary: 'Standard governing remaining useful life equations, short-term vs long-term corrosion rates, and MAWP derating protocols.',
    sampleChunks: [
      {
        id: 'chk-api-510-1',
        section: 'Section 1: Governing Remaining Useful Life (RUL) Equation',
        content: 'Remaining Life (Years) = (t_actual - t_required) / Corrosion_Rate. t_actual is measured at the most severely thinned structural sector; t_required is the minimum code thickness without corrosion allowance. Corrosion Rate is the conservative maximum of long-term and short-term rates.',
        relevanceTag: 'RUL Governing Formula',
      },
      {
        id: 'chk-api-510-2',
        section: 'Section 3: MAWP Derating Protocol',
        content: 'When actual wall thickness approaches t_required, Maximum Allowable Working Pressure (MAWP) must be officially derated using P_derated = (S * E * t_actual) / (R + 0.6 * t_actual). Pressure safety valves (PSVs) must be recalibrated downward to match.',
        relevanceTag: 'MAWP Recalculation',
      },
    ],
  },
  {
    id: 'asme-viii-shell',
    code: 'MRPL-STD-ASME-VIII',
    title: 'Cylindrical Shell Thickness & Stress Equations per ASME Section VIII',
    category: 'Inspection Code',
    unit: 'Technical Services / PV Eng',
    updatedAt: '2025-06-15',
    chunksCount: 4,
    summary: 'ASME Section VIII Div 1 (Part UG-27) circumferential and longitudinal stress formulas, joint efficiency ratings, and allowable stress tables.',
    sampleChunks: [
      {
        id: 'chk-asme-1',
        section: 'Section 1: Circumferential Stress Equation',
        content: 'For cylindrical shells under internal pressure, required wall thickness t is: t = (P * R) / (S * E - 0.6 * P). Where P is internal design pressure in MPa, R is inside radius before corrosion allowance, S is maximum allowable stress (138 MPa for SA-516 Gr 70 at 100C), and E is joint efficiency.',
        relevanceTag: 'Circumferential Stress Equation',
      },
    ],
  },
  {
    id: 'sop-hwp-108',
    code: 'MRPL-SOP-HWP-108',
    title: 'Hazardous Hot Work Permit & Toxic Gas Isolation Protocol',
    category: 'Hazardous Permit',
    unit: 'Refinery Wide / HSE',
    updatedAt: '2026-01-10',
    chunksCount: 4,
    summary: 'Procedures for Class-A hot work permits, continuous LEL and H2S gas monitoring limits, and positive blind flange isolation.',
    sampleChunks: [
      {
        id: 'chk-hwp-1',
        section: 'Section 2: Mandatory Atmospheric Gas Testing Limits',
        content: 'Prior to striking an arc or starting spark-producing machinery: Lower Explosive Limit (LEL) must read strictly 0.0%. H2S must be < 5.0 ppm. Oxygen content must be strictly between 19.5% and 21.0% by volume. Continuous gas monitoring with audible alarms must remain active.',
        relevanceTag: '0.0% LEL & H2S < 5ppm Limits',
      },
      {
        id: 'chk-hwp-2',
        section: 'Section 3: Isolation Requirements & Fire Watch',
        content: 'All process lines within 15 meters containing flammable vapors must be positively blinded with rated slip spades; valved isolation alone is strictly unacceptable. A dedicated Fire Watch with a 50kg DCP trolley must remain present.',
        relevanceTag: 'Spade Blinding Mandate',
      },
    ],
  },
  {
    id: 'sop-cru-101',
    code: 'MRPL-SOP-CRU-101',
    title: 'Atmospheric Distillation Column Startup & Pre-Heating Protocol',
    category: 'SOP',
    unit: 'CDU-II Fractionation Train',
    updatedAt: '2026-01-20',
    chunksCount: 4,
    summary: 'Pre-startup de-isolation, hot gas oil warming rate limits (25 C/hr), accumulator de-watering, and furnace pilot light-off safeguards.',
    sampleChunks: [
      {
        id: 'chk-cru-101-1',
        section: 'Section 2: Hot Oil Circulation & Reflux Drum De-Watering',
        content: 'Initiate hot gas oil circulation through boot coolers to warm shell courses gradually. Maximum allowable warming rate is 25 °C/hour to avoid differential thermal stress on clad plates. Sour water must be manually drained before reflux pump startup.',
        relevanceTag: '25 C/hr Warming Limit',
      },
    ],
  },
  {
    id: 'sop-hyc-205',
    code: 'MRPL-SOP-HYC-205',
    title: 'Hydrocracker Reactor High-Pressure Safeguarding',
    category: 'SOP',
    unit: 'Hydrocracker Unit (HCU)',
    updatedAt: '2025-10-12',
    chunksCount: 3,
    summary: 'Hydrogen partial pressure maintenance (>= 145 bar), catalyst bed exotherm quench rate triggers (2.5 C/min), and SIL-3 emergency depressurization (EDP).',
    sampleChunks: [
      {
        id: 'chk-hyc-1',
        section: 'Section 1: Operating Limits & Temperature Exotherm Quench',
        content: 'Operating hydrogen partial pressure must be maintained at >= 145.0 bar(g). If any catalyst bed exotherm rate exceeds 2.5 °C/minute, the automatic hydrogen quench control valve (HCV-2012) must be engaged to restore thermal equilibrium.',
        relevanceTag: 'Hydrogen Quench Trigger',
      },
    ],
  },
  {
    id: 'man-hex-220',
    code: 'MRPL-MAN-HEX-220',
    title: 'Shell & Tube Heat Exchanger Bundle Servicing (E-104 Series)',
    category: 'Equipment Manual',
    unit: 'Naphtha Hydrotreater / CDU',
    updatedAt: '2025-08-14',
    chunksCount: 4,
    summary: 'High-pressure hydrojetting (1,200 bar), pyrophoric scale neutralization, maximum allowable tube plugging (10.0%), and hydrostatic testing.',
    sampleChunks: [
      {
        id: 'chk-hex-1',
        section: 'Section 2: Maximum Allowable Tube Plugging Criteria',
        content: 'When eddy current testing reveals tube wall thinning exceeding 60% of original nominal gauge, tubes must be plugged. The maximum allowable cumulative plugged tubes across any individual bundle in the E-104 train is 10.0% of total tube count (64 out of 640 tubes).',
        relevanceTag: '10.0% Tube Plugging Limit',
      },
    ],
  },
  {
    id: 'man-pmp-112',
    code: 'MRPL-MAN-PMP-112',
    title: 'API 610 Centrifugal Process Pumps Vibration & Mechanical Seal Limits',
    category: 'Equipment Manual',
    unit: 'Machinery Maintenance Section',
    updatedAt: '2026-02-05',
    chunksCount: 4,
    summary: 'ISO 10816 vibration velocity trip limits (9.0 mm/s RMS), hydrodynamic bearing temperatures (max 95 C), and Plan 53B seal oil pressure (min 4.0 bar).',
    sampleChunks: [
      {
        id: 'chk-pmp-1',
        section: 'Section 1: Vibration Velocity Baselines & Trip Setpoints',
        content: 'Normal vibration velocity <= 3.0 mm/s RMS. Alert threshold between 4.5 and 7.1 mm/s RMS mandates daily FFT monitoring. Automatic machine trip occurs if vibration exceeds 9.0 mm/s RMS or bearing acceleration > 3.5 g pk-pk.',
        relevanceTag: 'Vibration Trip at 9.0 mm/s',
      },
      {
        id: 'chk-pmp-2',
        section: 'Section 3: Dual Mechanical Seal Barrier Fluid Requirements',
        content: 'Seal barrier oil pressure must be maintained at a minimum of 1.5 bar above maximum seal chamber pressure, and never lower than 4.0 bar(g) absolute. Barrier reservoir drop > 0.5 L/day indicates primary seal leakage.',
        relevanceTag: 'Seal Pressure Minimum 4.0 bar',
      },
    ],
  },
  {
    id: 'sop-cor-301',
    code: 'MRPL-SOP-COR-301',
    title: 'Online Corrosion Monitoring & Electrical Resistance (ER) Probes',
    category: 'SOP',
    unit: 'CDU / VDU Overhead Systems',
    updatedAt: '2025-11-18',
    chunksCount: 4,
    summary: 'Ammonium chloride and HCl dew-point corrosion monitoring, ER probe calibration, and critical rate alarm thresholds (> 0.30 mm/year).',
    sampleChunks: [
      {
        id: 'chk-cor-1',
        section: 'Section 2: Operating Baseline & Alarm Thresholds',
        content: 'Nominal allowable corrosion rate target is <= 0.12 mm/year for carbon steel overhead lines. Critical high corrosion alarm sounds if persistent rate exceeds 0.30 mm/year for > 48 hours, requiring wash water rate increase to 8.0% of crude volume.',
        relevanceTag: 'Corrosion Alarm at 0.30 mm/yr',
      },
    ],
  },
  {
    id: 'sop-tnk-501',
    code: 'MRPL-SOP-TNK-501',
    title: 'Tank Farm Crude Oil Receipt & High-High Level Safety',
    category: 'SOP',
    unit: 'Oil Movement & Storage (OM&S)',
    updatedAt: '2026-02-28',
    chunksCount: 3,
    summary: 'Single Point Mooring (SPM) pipeline line fill velocity (max 1.0 m/s), radar gauging, and SIL-2 independent high-high level slam shut (95%).',
    sampleChunks: [
      {
        id: 'chk-tnk-1',
        section: 'Section 2: Overfill Protection & Radar Gauging',
        content: 'Independent High-High Level Switch (LSHH, 95% capacity) initiates automatic slam-shut of inlet emergency isolation valve (EIV-502) within 15 seconds, independent of DCS control. Safe fill level is 90%.',
        relevanceTag: 'LSHH Overfill Protection (95%)',
      },
    ],
  },
  {
    id: 'corr-turnaround',
    code: 'MRPL-CORR-2026-08',
    title: 'Technical Memorandum: Turnaround Inspection Summary for Column CRU-C-101',
    category: 'Inspection Code',
    unit: 'Inspection Department',
    updatedAt: '2026-08-30',
    chunksCount: 5,
    summary: 'Memorandum from Chief Plant Inspector to Operations Manager summarizing UT findings: 7.82 mm wall thickness, 7.36 yr RUL, and interval reduction to 18M.',
    sampleChunks: [
      {
        id: 'chk-corr-1',
        section: 'Executive Brief',
        content: 'Measured Minimum Residual Thickness: 7.82 mm at Tray 14 (nominal 10.00 mm). Governing Retirement Thickness: 6.20 mm per ASME Section VIII. Remaining Useful Life: 7.36 years at 0.22 mm/yr corrosion rate. Mandates reducing turnaround inspection interval from 36M to 18M.',
        relevanceTag: 'CRU-C-101 Turnaround Findings',
      },
    ],
  },
  {
    id: 'sop-flr-001',
    code: 'MRPL-SOP-FLR-001',
    title: 'Refinery Flare Header Sweep & Liquid Knockout Drum Management',
    category: 'SOP',
    unit: 'Utilities & Offsites / Flare',
    updatedAt: '2025-12-01',
    chunksCount: 3,
    summary: 'Continuous flare purge sweep velocity (0.15 m/s), oxygen analyzer trip limits, and liquid knockout drum high level trips (85%).',
    sampleChunks: [
      {
        id: 'chk-flr-1',
        section: 'Section 1: Continuous Purge Gas Flow Requirements',
        content: 'Minimum header sweep purge velocity: 0.15 m/s under all ambient conditions to prevent flashback into the 42-inch flare header. Oxygen analyzer at stack base alarms at > 0.5% vol and trips supplemental sweep at > 1.0% vol O2.',
        relevanceTag: 'Flare Sweep Velocity 0.15 m/s',
      },
    ],
  },
];
